# 合约漏洞

## 重入漏洞

进行转账时调用了攻击合约的`fallback()`或`receive()`函数就会产生重入漏洞。

例：


## tx.origi权限控制漏洞

因为`tx.origin`是交易的原始发起者，而不是当前调用的合约地址。黑客就可以利用这个漏洞绕过权限检查。

下面这个合约就存在权限控制漏洞,这是一个钱包合约，部署
``` solidity
contract Wallet {
    address public owner;

    constructor() payable {
        owner = tx.origin;
    }

    function transfer(address payable _to, uint _amount) public {
        require(tx.origin == owner, "Not owner");
        (bool sent, ) = _to.call{value: _amount}("");
        require(sent, "Failed to send Ether");
    }
}
```


